-1001569413723:
  channel_name: 'SAMU.ZA'
  username: 'southafricanminorityunion'
  api_id: 24020245
-1001856125821:
  channel_name: 'Africa Intel'
  username: 'africaintel'
  api_id: 24020245
-1001176223343:
  channel_name: 'South Africa, future of the West 🇿🇦'
  username: 'ZA_future_of_the_West'
  api_id: 24020245
-1001101806611:
  channel_name: 'Boris Rozhin'
  username: "boris_rozhin"
  bias: 🇷🇺
  api_id: 23847013
-1001058013363:
  channel_name: 'CensorNet'
  username: "censor_net"
  bias: 🇺🇦
  api_id: 23847013
-1001669110938:
  channel_name: 'United24'
  username: "United24media"
  bias: 🇺🇦
  api_id: 23847013
-1001391125365:
  channel_name: 'TEST'
  username: "nn_test_channel"
-1001011817559:
  channel_name: Militarniy
  bloat:
#    - '@milinua'
    - 'Близький Схід українською\n<a href="https://t.me/MiddleEastinUkrainian">https://t.me/MiddleEastinUkrainian</a>'
  username: milinua
  bias: 🇺🇦
  api_id: 24020245